# The data type of input ids. 
input_dtype: "int64"
# Device to use. 
device: "gpu"
# infer batch size
infer_batch_size: 10

## max length of text
max_text_seqlen: 48
## text encoder vocabulary file
vocab_file: "./packages/ernie_base_3.0/vocab.txt"
## text encoder config
text_model_config: "./packages/ernie_base_3.0/ernie_config.base.json"
## test file 
test_file: "./packages/coco/your_data_path"
## output file path
output_file: "./test_out/cross_modal_embeddings.out"
## model_weights
init_from_params: "./params/your_model_weights_path"
## special token id for text
pad_token: 0
cls_token: 1
sep_token: 2
mask_token: 3
unk_token: 17963